DCIS_Syllabus/Controllers/Course_OutcomesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using DCIS_Syllabus;
using DCIS_Syllabus.ViewModel;

namespace DCIS_Syllabus.Controllers
{
    public class Course_OutcomesController : Controller
    {
        private Syllabus_ManagementEntities4 db = new Syllabus_ManagementEntities4();

        // GET: Course_Outcomes
        public ActionResult Index()
        {
            var course_Outcomes = db.Course_Outcomes.Include(c => c.Syllabu);
            return View(course_Outcomes.ToList());

        }


        // GET: Course_Outcomes/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Course_Outcomes course_Outcomes = db.Course_Outcomes.Find(id);
            if (course_Outcomes == null)
            {
                return HttpNotFound();
            }
            return View(course_Outcomes);
        }

        // GET: Course_Outcomes/Create
        public ActionResult Create()
        {
            ViewBag.syllabus_FK = new SelectList(db.Syllabus, "syllabus_ID", "title");
            return View();
        }

        // POST: Course_Outcomes/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "courseOutcomes_ID,syllabus_FK,codeName,outcomeDescription,domainLearningLVL")] Course_Outcomes course_Outcomes)
        {
            if (ModelState.IsValid)
            {
                db.Course_Outcomes.Add(course_Outcomes);
                db.SaveChanges();

                db.Entry(course_Outcomes).GetDatabaseValues();
                int newID = course_Outcomes.courseOutcomes_ID;
                int numOfPO = db.Program_Outcomes.Select(d => d.code_outcome).Distinct().Count();
                int syllabusID = course_Outcomes.syllabus_FK;
                PopulateModels(numOfPO, newID);

                return RedirectToAction("ShowResults", "Active_Values", new { id = syllabusID});
            }

            ViewBag.syllabus_FK = new SelectList(db.Syllabus, "syllabus_ID", "title", course_Outcomes.syllabus_FK);
            return View(course_Outcomes);
        }
        

        private void PopulateModels(int numOfPO, int courseOutcomes_ID)
        {
            //List<Active_Values> modelActiveModels = new List<Active_Values>();

            string[] colName = { "S", "V", "D" };
            int j = 1;
            for (int i = 0; i < numOfPO; i++) //the first three does not have columnName
            {
                Active_Values av = new Active_Values();
                if (i < 3)
                {
                    av.columnName = colName[i];
                }
                else
                {
                    av.columnName = j.ToString();
                    
                    j++;
                }

                av.programOutcomeAbbr = " ";
                av.activeStatus = "false";
                av.courseOutcomes_FK = courseOutcomes_ID;
                db.Active_Values.Add(av);
                db.SaveChanges();
            }


        }

        // GET: Course_Outcomes/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Course_Outcomes course_Outcomes = db.Course_Outcomes.Find(id);
            if (course_Outcomes == null)
            {
                return HttpNotFound();
            }
            ViewBag.syllabus_FK = new SelectList(db.Syllabus, "syllabus_ID", "title", course_Outcomes.syllabus_FK);
            return View(course_Outcomes);
        }

        // POST: Course_Outcomes/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "courseOutcomes_ID,syllabus_FK,codeName,outcomeDescription,domainLearningLVL")] Course_Outcomes course_Outcomes)
        {
            if (ModelState.IsValid)
            {
                db.Entry(course_Outcomes).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.syllabus_FK = new SelectList(db.Syllabus, "syllabus_ID", "title", course_Outcomes.syllabus_FK);
            return View(course_Outcomes);
        }

        // GET: Course_Outcomes/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Course_Outcomes course_Outcomes = db.Course_Outcomes.Find(id);
            if (course_Outcomes == null)
            {
                return HttpNotFound();
            }
            return View(course_Outcomes);
        }

        // POST: Course_Outcomes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Course_Outcomes course_Outcomes = db.Course_Outcomes.Find(id);
            db.Course_Outcomes.Remove(course_Outcomes);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

DCIS_Syllabus/Controllers/TeacherAndCoordinatorView/InstGradAttrbController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DCIS_Syllabus.Controllers
{
    public class InstGradAttrbController : Controller
    {
        // GET: InstGradAttrb
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult InstGradAttrb()
        {
            //connect to db
            Syllabus_ManagementEntities1 syllabus = new Syllabus_ManagementEntities1();
            //retrieve table details (firstName, lastName, etc.) -- what table?
            Core_Value value = new Core_Value();

            //from the table friends, select all in descending order by age
            var core_valueList = (from u in syllabus.Core_Value
                                  select u);

            //converting all the retrieved data (friends) into a list object
            ViewData["CoreValueList"] = core_valueList.ToList();
            return View();
        }
    }
}

DCIS_Syllabus/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Styles.Render("~/Content/SyllabusIndex.css")
    @Styles.Render("~/Content/InstGradAttrb/IGA.css")
    @Styles.Render("~/Content/LearningPlan/LP.css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Syllabus - T", "ViewAllTSyllabus", "Teacher")</li>
                    <li>@Html.ActionLink("Syllabus - Ch", "ViewAllChSyllabus", "Chairman")</li>
                    <li>@Html.ActionLink("Create Syllabus", "Creation", "Teacher")</li>
                    <li>@Html.ActionLink("Program Objecives", "ProgramObj2", "Chairman")</li>
                </ul>
            </div>
        </div>
    </div>

    <div class="main">
        @RenderBody()
        <hr />
        <footer>
            
        </footer>
    </div>

    @Scripts.Render("~/Scripts/jquery.js")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/Scripts/TeacherScript.js")
    @Scripts.Render("~/Scripts/learningplan.js")
    @RenderSection("scripts", required: false)



</body>
</html>

DCIS_Syllabus/Views/Shared/_SideBar.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Styles.Render("~/Content/SyllabusIndex.css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>sss

    <h2>_SideBar</h2>

    <div class="sidenav">
        <ul>

            <li>@Html.ActionLink("Add Classroom Policy", "ClassroomPolicy", "Teacher")</li>
            <li>@Html.ActionLink("Institutional Graduate Attributes", "InstGradAttrb", "InstGradAttrb")</li>
            <li>@Html.ActionLink("Program Outcomes", "program_outcomes", "Teacher")</li>
            <li>@Html.ActionLink("Learning Plan", "LearningPlan", "LearningPlan")</li>
            <li>@Html.ActionLink("Revision History", "revision_history", "Teacher")</li>
            <li>@Html.ActionLink("Course Outcomes", "Create", "Course_Outcomes")</li>
            <li>@Html.ActionLink("Grading System", "grading_system", "Teacher")</li>
            <li>@Html.ActionLink("Assessment Criteria", "AssessmentCriteria", "Teacher")</li>
            <li>@Html.ActionLink("Deliverable O and R", "outputs_requirements", "Teacher")</li>
            <li>@Html.ActionLink("Bibliography", "Bibliography", "Teacher")</li>
            <li>@Html.ActionLink("Software Used", "SoftwareUsed", "SoftwareUsed")</li>
            <li>@Html.ActionLink("Program Outcomes", "program_outcomes", "Teacher")</li>
            <li>@Html.ActionLink("Program Objecives", "ProgramObj2", "Chairman")</li>

        </ul>
        <a>@Html.ActionLink("Back", "Index", "Home")</a>


    </div>

    <div class="main">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/Scripts/jquery.js")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/Scripts/TeacherScript.js")
    @RenderSection("scripts", required: false)



</body>
</html>