DCIS_Syllabus/Controllers/Active_ValuesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using DCIS_Syllabus;
using DCIS_Syllabus.ViewModel;

namespace DCIS_Syllabus.Controllers
{
    public class Active_ValuesController : Controller
    {
        private Syllabus_ManagementEntities4 db = new Syllabus_ManagementEntities4();

        // GET: Active_Values
        public ActionResult Index()
        {
            var active_Values = db.Active_Values.Include(a => a.Course_Outcomes);
            return View(active_Values.ToList());
        }

        /// <summary>
        /// This looks for a specific course outcome with all active values d
        /// </summary>
        /// <param name="activeModel"></param>
        /// <returns></returns>
       /* public ActionResult ShowResults(Active_Values activeModel)//find all activeValues of courseID
        {
            var viewModel = new CourseOutcomesIndex
            {
                activeValues = db.Active_Values
                .Where(i => i.courseOutcomes_FK == activeModel.courseOutcomes_FK),
                courses = db.Course_Outcomes
                .Where(i => i.courseOutcomes_ID == activeModel.courseOutcomes_FK)
              };

            ViewBag.course_ID = activeModel.courseOutcomes_FK;
            return View("ShowResults", viewModel);
        }*/

        public ActionResult ShowResults(int id)//find all activeValues of courseID
        {
            //if(id != null)
            //{

            var viewmodel1 = new CourseOutcomesIndex();
            viewmodel1.courses = db.Course_Outcomes.Include(i => i.Active_Values)
                          .Where(i => i.syllabus_FK == id);
            //}
            viewmodel1.activeValues = db.Active_Values
                                    .Join(db.Course_Outcomes, a => a.courseOutcomes_FK, b => b.courseOutcomes_ID, 
                                    (a, b) => a);
            //ViewBag.course_ID = viewModel.ElementAt(1).activeValues.ElementAt(1).courseOutcomes_FK;     
            return View("ShowResults", viewmodel1);
        }

        // GET: Active_Values/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Active_Values active_Values = db.Active_Values.Find(id);
            if (active_Values == null)
            {
                return HttpNotFound();
            }
            return View(active_Values);
        }

        // GET: Active_Values/Create
        public ActionResult CreateActiveValues(int id)
        {
            ViewBag.courseOutcomes_FK = id;
            ViewBag.columnName = new SelectList(db.Core_Value, "coreValue_ID", "name");
            //ViewBag.courseOutcomes_FK = new SelectList(db.Course_Outcomes, "courseOutcomes_ID", "codeName");
            return View();
        }

        // POST: Active_Values/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "activeValues_ID,columnName,programOutcomeAbbr,activeStatus,courseOutcomes_FK")] Active_Values active_Values)
        {
            if (ModelState.IsValid)
            {
                db.Active_Values.Add(active_Values);
                db.SaveChanges();
                return RedirectToAction("ShowResults",active_Values);
            }

            ViewBag.courseOutcomes_FK = new SelectList(db.Course_Outcomes, "courseOutcomes_ID", "codeName", active_Values.courseOutcomes_FK);
            return View(active_Values);
        }

        // GET: Active_Values/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Active_Values active_Values = db.Active_Values.Find(id);
            if (active_Values == null)
            {
                return HttpNotFound();
            }
            ViewBag.courseOutcomes_FK = new SelectList(db.Course_Outcomes, "courseOutcomes_ID", "codeName", active_Values.courseOutcomes_FK);
            return View(active_Values);
        }

        // POST: Active_Values/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "activeValues_ID,columnName,programOutcomeAbbr,activeStatus,courseOutcomes_FK")] Active_Values active_Values)
        {
            if (ModelState.IsValid)
            {
                db.Entry(active_Values).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.courseOutcomes_FK = new SelectList(db.Course_Outcomes, "courseOutcomes_ID", "codeName", active_Values.courseOutcomes_FK);
            return View(active_Values);
        }

        // GET: Active_Values/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Active_Values active_Values = db.Active_Values.Find(id);
            if (active_Values == null)
            {
                return HttpNotFound();
            }
            return View(active_Values);
        }

        // POST: Active_Values/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Active_Values active_Values = db.Active_Values.Find(id);
            db.Active_Values.Remove(active_Values);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

DCIS_Syllabus/Views/Active_Values/CreateActiveValues.cshtml
@model DCIS_Syllabus.Active_Values

@{
    ViewBag.Title = "Create Core Values Activated";
    Layout = "~/Views/Shared/_SideBar.cshtml";
}

<h2>Create</h2>


        @using (Html.BeginForm("Create", "Active_Values", FormMethod.Post))
        {
            @Html.AntiForgeryToken()

            <div class="form-horizontal">
                <h4>Active_Values</h4>
                <hr />
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="form-group">
                    @Html.LabelFor(model => model.columnName, htmlAttributes: new { @class = "control-label col-md-2" })
                    <label class="control-label col-md-2" for="columnName">Core Value</label>
                    <div class="col-md-10">
                        @Html.DropDownList("columnName", null, htmlAttributes: new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.columnName)
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.programOutcomeAbbr, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.programOutcomeAbbr, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.programOutcomeAbbr, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.activeStatus, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.activeStatus, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.activeStatus, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.courseOutcomes_FK, "courseOutcomes_FK", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.courseOutcomes_FK, new { htmlAttributes = new { @class = "form-control read-only", @Value = @ViewBag.courseOutcomes_FK } })
                        @Html.ValidationMessageFor(model => model.courseOutcomes_FK, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Create" class="btn btn-default" />
                    </div>
                </div>
            </div>
        }

    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>

DCIS_Syllabus/Views/Active_Values/Delete.cshtml
@model DCIS_Syllabus.Active_Values

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_SideBar.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Active_Values</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.columnName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.columnName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.programOutcomeAbbr)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.programOutcomeAbbr)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.activeStatus)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.activeStatus)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Course_Outcomes.codeName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Course_Outcomes.codeName)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

DCIS_Syllabus/Views/Active_Values/Details.cshtml
@model DCIS_Syllabus.Active_Values

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_SideBar.cshtml";
}

<h2>Details</h2>

<div>
    <h4>Active_Values</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.columnName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.columnName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.programOutcomeAbbr)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.programOutcomeAbbr)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.activeStatus)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.activeStatus)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Course_Outcomes.codeName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Course_Outcomes.codeName)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.activeValues_ID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

DCIS_Syllabus/Views/Active_Values/Edit.cshtml
@model DCIS_Syllabus.Active_Values

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_SideBar.cshtml";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Active_Values</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.activeValues_ID)

        <div class="form-group">
            @Html.LabelFor(model => model.columnName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.columnName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.columnName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.programOutcomeAbbr, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.programOutcomeAbbr, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.programOutcomeAbbr, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.activeStatus, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.activeStatus, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.activeStatus, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.courseOutcomes_FK, "courseOutcomes_FK", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("courseOutcomes_FK", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.courseOutcomes_FK, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

DCIS_Syllabus/Views/Active_Values/Index.cshtml
@model IEnumerable<DCIS_Syllabus.Active_Values>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_SideBar.cshtml";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.columnName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.programOutcomeAbbr)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.activeStatus)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Course_Outcomes.codeName)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.columnName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.programOutcomeAbbr)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.activeStatus)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Course_Outcomes.codeName)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.activeValues_ID }) |
            @Html.ActionLink("Details", "Details", new { id=item.activeValues_ID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.activeValues_ID })
        </td>
    </tr>
}

</table>

DCIS_Syllabus/Views/Active_Values/ShowResults.cshtml
@model DCIS_Syllabus.ViewModel.CourseOutcomesIndex
@{
    ViewBag.Title = "ShowResults";
    Layout = "~/Views/Shared/_SideBar.cshtml";
}

<h2>ShowResults</h2>



<table id="myTable" class=" table" border="1">
    <thead>
        <tr>
            <th colspan="1">Code</th>
            <th colspan="1">Course Outcomes</th>
            <th colspan="1">Domain of Learning & Level</th>
        </tr>
        <tr>
            <td><p>Upon completion</p></td>
            <td></td>
            <td>
                S
            </td>
            <td>
                V
            </td>
            <td>
                D
            </td>
        </tr>
    </thead>

    <tr>
        @foreach (var item in Model.courses)
        {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.codeName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.outcomeDescription)
            </td>
           
            <td>
                @Html.DisplayFor(modelItem => item.domainLearningLVL)
            </td>
            }

        </tr>

            }


    </tr>
    </table>
<table>
    <thead>
        <tr>
         <th colspan="3">Core Values Activated</th>
         <th colspan="10">Program Outcomes (POs) Activated</th>
        </tr>
    </thead>
    <tr>
        @foreach (var activeItem in Model.activeValues)
        {
            
            <td>
                @Html.DisplayFor(modelItem => activeItem.columnName)
            </td>


        }
    </tr>
</table>